### PR TITLE
Use Firefox themes

### LINKED ISSUE #5: Usability: change column header 'Count' to 'Violations'
'Count' is unclear - a count of what? As it's a count of the number of violations for a given criterion, naming the column 'Violations' would be more descriptive.

'Count' column header

### LINKED ISSUE #6: Usability: heading for violation details is unclear
Violation details are labeled simply "17 of 23" with no descriptive text. Recommendations:

1. Repeat the description of the criterion above the violation navigation so that users have a more obvious reference to what they're looking at.
2. Label the violation navigation something like "Viewing violation 17 of 23".

Violation navigation:
violation navigation

### LINKED ISSUE #7: Usability: Default font size should be larger.
The font size for all text is very small at 100% zoom. Would recommend using a font size at least as big as is used for the developer tool headers. The font size should at least 12px; ideally 16px.

Font size very small compared to headings:
font size

### LINKED ISSUE #10: Opening aXe Panel on about:blank throws exception
Steps:
1.  `jpm run`
2.  Open Dev Tools and select Accessibility panel

```
console.error: axe-firefox-devtools: 
JPM undefined   Message: TypeError: workerEntry is undefined
  Stack:
    AxePanel<.onReady@resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-cejgfwewyx7kwa-at-jetpack/lib/main.js:182:3
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:104:9
onStateChange@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/dev/panel.js:70:3
```

### LINKED ISSUE #13: Theme
https://github.com/mozilla/gecko-dev/blob/b6ea902b969546b6ae6c2d43e68b193bfb48716e/browser/devtools/shared/theme-switching.js

### LINKED ISSUE #14: a11y: Add a menuitem which opens and sends focus to aXe

### LINKED ISSUE #15: a11y/usability: "Analysis in progress" message
1.  Should communicate to screen readers
2.  Should send focus to result set when complete

### PR DESCRIPTION
**Pull request by dsturley**
Also:

* Add menuitem to Tools > Web Developer > Accessibility Audit
* Stable messaging (using postMessage)
* Redesign to fit Firefox theme and make respondable
* Do not use SDK for panel creation

Resolves #15 
Resolves #14 
Resolves #13 
Resolves #10 
Resolves #7 
Resolves #6 
Resolves #5

### CODE REVIEW

File: data/panel/panel.js [hunk 1]
```diff
@@ -0,0 +1,204 @@
...
+      Array.prototype.slice.call(document.querySelectorAll('.selected')).forEach(function(node) {
+        node.classList.remove('selected');
+        node.removeAttribute('title');
+      });
+      target.parentNode.classList.add('selected');
+      target.setAttribute('title', 'selected');
+      return;
+    }
+
+		if (e.target.classList.contains('axe-analyze-button')) {
```
Comment (dylanb) [inline data/panel/panel.js]: tab problems

File: data/panel/panel.js [hunk 2]
```diff
@@ -0,0 +1,204 @@
...
+      node: node
+    });
+    bindButtons(node.target);
+    window.postMessage({
+      "command": "highlight",
+      "target": "addon",
+      "node": node.target
+    }, '*');
+  }
+	function receive(event) {
```
Comment (dylanb) [inline data/panel/panel.js]: more tab noise
